site_name: HuHoBot Docs
site_author: 'HuoHuas001'
site_description: 'HuHoBot 说明文档'
site_url: 'https://huhobot.txssb.cn/'
copyright: Copyright © 2025 HuoHuas001

nav:
  - 主页: index.md
  - 快速开始: QuickStart/index.md
  - 常见问题: Question/index.md
  - 附属插件列表: plugins.md
  - 管理员帮助: AdminHelp/index.md
  - 适配器指南:
    - 主页: Adapter/index.md
    - Spigot: Adapter/Spigot.md
    - LSE: Adapter/LSE.md
    - EndStone: Adapter/EndStone.md
    - Allay: Adapter/Allay.md
    - Nukkit-MOT: Adapter/Nukkit-MOT.md
    - 第三方: Adapter/Third-Party.md
  - 附属插件开发指南:
    - 数据包: Develop/DataPack.md
    - 事件: Develop/Events.md
    - Spigot: Develop/Spigot.md
    - LSE: Develop/LSE.md
    - Allay: Develop/Allay.md
  - 协议开发指南:
    - 主页: Protocol/index.md
    - 请求: Protocol/requests.md
    - 事件: Protocol/events.md
  - 赞助HuHoBot: Sponsor.md


theme:
  name: material
  logo: img/logo.png
  favicon: img/logo.png
  #locale: zh_CN
  icon:
    repo: fontawesome/brands/github
  highlightjs: true
  hljs_languages:
    - yaml
    - rust
    - python
    - cpp
    - java
    - bash


markdown_extensions:
  - toc:
      permalink: True
  - footnotes
  - tables
  - admonition  # 提示块
  - meta  # 定义元数据，通过文章上下文控制，如disqus
  - pymdownx.caret  # 下划线上标
  - pymdownx.tilde  # 删除线下标
  - pymdownx.critic  # 增加删除修改高亮注释，可修饰行内或段落
  - pymdownx.details  # 提示块可折叠
  - pymdownx.inlinehilite  # 行内代码高亮
  - pymdownx.mark  # 文本高亮
  - pymdownx.smartsymbols  # 符号转换
  - pymdownx.superfences  # 代码嵌套在列表里
  - codehilite:    # 代码高亮，显示行号
      guess_lang: false
      linenums: true
#  - pymdownx.arithmatex  # 数学公式
  - pymdownx.betterem:  # 对加粗和斜体更好的检测
      smart_enable: all
#  - pymdownx.emoji:  # 表情
#      emoji_generator: !!python/name:pymdownx.emoji.to_svg
#  - pymdownx.magiclink  # 自动识别超链接
  - pymdownx.tasklist:  # 复选框checklist
      custom_checkbox: true
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  
plugins:
  - search

repo_url: https://github.com/HuHoBot

repo_name: HuHoBot Repo

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/highlight.min.js
  - javascripts/config.js
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/styles/default.min.css