[UserWhiteList]
description = "让玩家可以在群内自主添加白名单"
authors = ["HuoHuas001"]
github = "https://github.com/HuHoBot/ExpansionPlugin/tree/main/HuHoBot_RC_WhiteList"
adapter = "Lse"

[HuHoMonitor-Spigot]
description = "HuHoBot服务器状态信息查询插件"
authors = ["HuoHuas001"]
github = "https://github.com/HuHoBot/HuHoMonitor"
adapter = "Spigot"

[HuHoMonitor-Lse]
description = "HuHoBot服务器状态信息查询插件"
authors = ["HuoHuas001"]
github = "https://github.com/HuHoBot/ExpansionPlugin/tree/main/HuHoMonitor"
adapter = "Lse"

[HuHoWhiteList-Spigot]
description = "HuHoBot自助申请白名单插件"
authors = ["HuoHuas001"]
github = "https://github.com/HuHoBot/HuHoWhiteList"
adapter = "Spigot"

[HuHoWhiteList-Lse]
description = "HuHoBot自助申请白名单插件"
authors = ["HuoHuas001"]
github = "https://github.com/HuHoBot/ExpansionPlugin/tree/main/HuHoWhiteList"
adapter = "Lse"

